### ISSUE TITLE
[Enhancement] Support 2FA

### ISSUE THREAD

**Issue by ceciliastevens** [code42/py42#195]
## Summary
Code42 supports [two-factor authentication](https://support.code42.com/Administrator/Cloud/Configuring/Two-factor_authentication_for_local_users) for locally-authorized accounts. Py42 currently errors out if you attempt to set up an SDK connection using an account with two-factor.

We could investigate implementing support for accounts which require this auth type.

## Proposed API

By default, if a user requires 2FA, prompt them:

```
>>> c42 = sdk.from_local_account(hostAddress, username, password)
Please input your authentication code: ******
>>> c42.user.get_current()
```

After time has passed, prompt again if necessary when renewing the v3_user_token.

Additionally, accept an optional function that returns the 2FA code (for automation):

```
>>> c42 = sdk.from_local_account(hostAddress, username, password, totp_function)
>>> c42.user.get_current()
```

If a function is provided, it will be called again when the token needs to be renewed, allowing developers to provide interfaces to alternative TOTP solutions/implementations.

## Intended Use Case
This could be used by Code42 users who wish to automate API interactions, but also want an additional layer of security protecting API accounts.

**Comment by alanag13** [comment]
Hi @ceciliastevens,

Thanks for sharing this request. I don't think we would go the route of prompting within py42 itself because if any of our integrations accidentally used a 2FA user this would cause the app / script etc to hang forever as it waits for input.

Instead, I'm thinking we would add an optional `totp_code` argument to `from_local_account`. The workflow would be something like:

```python
try:
    c42 = sdk.from_local_account(hostAddress, username, password)
except Py42MFARequiredError: # new exception type
   # user handles this on their own instead of having it be baked into py42
    code = input("Please input your authentication code:")
    c42 = sdk.from_local_account(hostAddress, username, password, totp_code=code)
```
> Additionally, accept an optional function that returns the 2FA code (for automation):
> If a function is provided, it will be called again when the token needs to be renewed, allowing developers to provide interfaces to alternative TOTP solutions/implementations.

There is not a way to programmatically retrieve a user's 2FA code. If there was, it would defeat the whole purpose of 2FA! So, one limitation to be aware of even if we implemented the above approach would be that auto-renewing the authentication would not be possible when using 2FA.

**Comment by ceciliastevens** [comment]
> There is not a way to programmatically retrieve a user's 2FA code. If there was, it would defeat the whole purpose of 2FA! So, one limitation to be aware of even if we implemented the above approach would be that auto-renewing the authentication would not be possible when using 2FA.

I've seen customers in the past have other applications generate their 2FA code (i.e. using onepassword or something instead of an authenticator app on the phone), I was imagining some sort of interface with whatever other system they've got for managing that.

**Comment by alanag13** [comment]
> > There is not a way to programmatically retrieve a user's 2FA code. If there was, it would defeat the whole purpose of 2FA! So, one limitation to be aware of even if we implemented the above approach would be that auto-renewing the authentication would not be possible when using 2FA.
> 
> I've seen customers in the past have other applications generate their 2FA code (i.e. using onepassword or something instead of an authenticator app on the phone), I was imagining some sort of interface with whatever other system they've got for managing that.

Ah, that makes a little more sense, you are probably thinking of something like https://totp.app/, which allows you to decide the secret key that is used generate your totp. This would technically be possible if the user had their secret key, but in many cases (like with the authenticator app), the secret key is generated for them by a third party and is unknown to them. Since that would be a function that the user would have to provide, they'd have to look into how to implement that, but I'm willing to look at passing that function itself more closely as a feature possibility.
