### ISSUE TITLE
[Bug] settings.proxy is not supported.

### ISSUE THREAD

**Issue by csanders-git** [code42/py42#226]
### Description

The settings.proxy option isn't used to overwrite the requests proxy setting as described by the documentation. As you can see at https://github.com/code42/py42/blob/765dee58c90b4e53ea224e95c7d4662193243e62/src/py42/services/_connection.py#L170 - The connection request function takes a proxy which defaults to None. It is this parameter that is passed to proxies, not `settings.proxies`. When looking at the calls to this you can see that no function passes settings.proxies as would be needed for this feature to work.

### Steps to Reproduce

```
settings.proxy = {
  'http': 'http://127.0.0.1:8080',
  'https': 'http://127.0.0.1:8080',
}
sdk = py42.sdk.from_local_account()
users = sdk.users
for page in users.get_all():
    print("Not proxied")
```

### Expected Behavior
The response would be proxied

### Actual Behavior
The proxies are ignored.

### Basic Information

- py42 version: 1.9.0
- python version: 3.8.6
- operating system: MacOS 10.15

**Comment by alanag13** [comment]
@csanders-git wow, good find! I suspect that some refactoring took place at some point caused this. We'll definitely get this corrected.

**Comment by alanag13** [comment]
@csanders-git I noticed that your issue title and description mention the setting as being named `settings.proxy`, but the actual name is `settings.proxies`. Are you referencing the wrong attribute?

I still need to test this out physically, but `settings.proxies` does get set on the session (rather than the request) during `_prepare_request` here:https://github.com/code42/py42/blob/765dee58c90b4e53ea224e95c7d4662193243e62/src/py42/services/_connection.py#L201

I _think_ the intention was that the request-level proxy would override the session-level one if it was passed for a specific request, we'll need to look into if the actual behavior doesn't work that way.

**Comment by csanders-git** [comment]
Oh wow, this could easily be my fault for not groking the readme correctly. I'm running through analysis now but once the code is done running i'll retest this. Hopefully this can be quickly closed, thanks @alanag13

**Comment by csanders-git** [comment]
verified that this was a typo on my end settings.proxies resolved the issue thanks @alanag13
